version: "3"
services:
  ima-guacd:
    container_name: ima-guacd
    hostname: ima-guacd
    image: guacamole/guacd
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      GUACD_LOG_LEVEL: debug
    networks:
      guacnetwork:

  ima-guacdb:
    container_name: ima-guacdb
    hostname: ima-guacdb
    tty: true
    stdin_open: true 
    restart: unless-stopped 
    image: mysql
    environment:
      ACCEPT_EULA: Y
      MYSQL_ROOT_PASSWORD: P4Ssw0rdR00t22
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: p4SguaCamol33
    volumes:
      - ima-guacdb_db:/var/lib/mysql
    networks:
      guacnetwork:

  ima-guacamole:
    container_name: ima-guacamole
    hostname: ima-guacamole
    tty: true
    stdin_open: true
    image: guacamole/guacamole
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ACCEPT_EULA: Y
      GUACD_HOSTNAME: ima-guacd
      MYSQL_HOSTNAME: ima-guacdb
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: p4SguaCamol33
    depends_on:
      - ima-guacdb
      - ima-guacd
    links:
      - ima-guacd:guacd
      - ima-guacdb:mysql
    volumes:
      - ./app/opt:/opt/guacamole
      - ./app/home:/home/guacamole
    networks:
      guacnetwork:
      
volumes:
  ima-guacdb_db:

networks:
  guacnetwork:
    driver: bridge