version: '3'
services:

  guacdb:
    container_name: guacdb
    image: 'gitlab-reg.imagar.com/sistemas1/guacamole/guacamole-project/mariadb:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'MariaDBRootPSW'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'guacamole_user' #guacamole_user
      MYSQL_PASSWORD: 'MariaDBUserPSW' #MariaDBUserPSW
    volumes:
      - 'guacdb-data:/var/lib/mysql'

  guacd:
    container_name: guacd
    image: 'gitlab-reg.imagar.com/sistemas1/guacamole/guacamole-project/guacd:latest'
    restart: unless-stopped

  guacamole:
    container_name: guacamole
    image: 'gitlab-reg.imagar.com/sistemas1/guacamole/guacamole-project/guacamoleclient15:latest'
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      GUACD_HOSTNAME: "guacd"
      MYSQL_HOSTNAME: "guacdb"
      MYSQL_DATABASE: "guacamole_db"
      MYSQL_USER: "guacamole_user" #guacamole_user
      MYSQL_PASSWORD: "MariaDBUserPSW" #MariaDBUserPSW
    depends_on:
      - guacdb
      - guacd

volumes:
  guacdb-data: